### ISSUE TITLE
Openat syscall is not supported

### ISSUE THREAD

**Issue by nponeccop** [johnlcf/Stana#4]
Modern glibc uses `openat` syscall in place of `open`. So basically anywhere where `open` is expected, `openat` should be expected as well, because modern kernels support them both.

**Comment by johnlcf** [comment]
Thanks for using Stana and reporting this. You are right. I just updated the code.

BTW, I see you have a blog post in https://nponeccop.livejournal.com/ which seems to be related to this. (I try google translate it to English). I would be very happy if you can share the whole story with me in English because I would like to how people is using my project. :-)

**Comment by nponeccop** [comment]
That post https://nponeccop.livejournal.com/592005.html is only a rant, it doesn't contain useful info :)

I don't use Stana either - the script mentioned in the post is https://github.com/nponeccop/vz/blob/c934e3038a6a81e33886f9a505d2deab8da85ddf/future/vzbuild/strace-parse.sh which is a simple grep/sed oneliner.

I wanted to move to something more reliable though, and that's how I encountered Stana.

**Comment by johnlcf** [comment]
I see. :-)
Hope Stana can help.
