### ISSUE TITLE
Missed openat lines

### ISSUE THREAD

**Issue by nponeccop** [johnlcf/Stana#6]
Apparently Stana doesn't recognize lines like this one, while some other `openat` calls work just fine.

```
13966 openat(AT_FDCWD, "/home/foo/bar/quux/newroot/var/lib/pacman/local/ALPM_DB_VERSION", O_WRONLY|O_CREAT|O_TRUNC|O_LARGEFILE, 0666) = 3
```

**Comment by nponeccop** [comment]
Note that some `openat` calls have the mode (like `0666` here) but some don't, in the same trace!

**Comment by johnlcf** [comment]
I manually put your line in one of my test strace file, and run ./strace_analyser -e StatFileIO <file>, and it recognizes that line properly. Have you checkout the latest version?
Which plugin you are using? And do you see any error message?
Or you can send your strace file to me and tell me the command you run so that I can try reproduce the problem.

**Comment by nponeccop** [comment]
Oh somehow the line alone works for me too. The following trace doesn't work:
```
13954 openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
13954 openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
```

```
$ python2 ./strace_analyser -e StatFileIO test-trace
====== File IO summary (csv) ======
filename, open/close count, read count, read bytes, write count, write bytes
"/etc/ld.so.cache", 1, 0, 0, 0, 0
```

**Comment by johnlcf** [comment]
I think I know why. The StatFileIO plugin assume the strace has "close" syscalls. But your strace doesn't contains the "close" system calls. I can try to fix the plugin so that it can still partially work if there is only open/openat calls. But I think the plugin works best if you trace all "read", "write", "open", "openat", "close" calls.

**Comment by nponeccop** [comment]
Well, lots of software relies on handles being closed by OS or runs forever. So waiting for closing is not an option. I think the best scenario for me then is to write a custom plugin.

Feel free to close this issue then
